from enum import StrEnum

class Ticker(StrEnum):
    ACB = "ACB"
    BID = "BID"
    BSR = "BSR"
    CTG = "CTG"
    FPT = "FPT"
    GAS = "GAS"
    GVR = "GVR"
    HDB = "HDB"
    HPG = "HPG"
    LPB = "LPB"
    MBB = "MBB"
    MCH = "MCH"
    MSN = "MSN"
    MWG = "MWG"
    SAB = "SAB"
    SHB = "SHB"
    SSB = "SSB"
    SSI = "SSI"
    STB = "STB"
    TCB = "TCB"
    TCX = "TCX"
    VCB = "VCB"
    VHM = "VHM"
    VIB = "VIB"
    VIC = "VIC"
    VJC = "VJC"
    VNM = "VNM"
    VPB = "VPB"
    VPL = "VPL"
    VRE = "VRE"


class Concept(StrEnum):
    BANKING = "BANKING"
    CONSUMER_DISCRETIONARY = "CONSUMER_DISCRETIONARY"
    CONSUMER_STAPLES = "CONSUMER_STAPLES"
    ENERGY = "ENERGY"
    INDUSTRIALS = "INDUSTRIALS"
    MACRO = "MACRO"
    MATERIALS = "MATERIALS"
    REAL_ESTATE = "REAL_ESTATE"
    SECURITIES = "SECURITIES"
    TECHNOLOGY = "TECHNOLOGY"
